stages:
  - build

variables:
  BUILD_NAME: backports2
  HADOOP_VERSION: "3.3.5"
  SPARK_VERSION: "3.4.0"
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

build:
  stage: build
  tags:
    - docker
  image: ubuntu:jammy
  script:
    - apt-get update
    - apt-get install -y curl git python3 python3-pip openjdk-8-jdk-headless
    - ./dev/make-distribution.sh --name $BUILD_NAME --pip --tgz -Phive -Phive-thriftserver -Phadoop-provided -Pyarn -Phadoop-cloud -Dhadoop.version=$HADOOP_VERSION
  artifacts:
    paths:
      - spark-$SPARK_VERSION-bin-$BUILD_NAME.tgz
    expire_in: 1 day
  cache:
    key: maven
    paths:
      - .m2/repository
